language: java

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

jobs:
  include:
    - stage: build
      script: ./gradlew clean assemble
    - stage: test
      script: ./gradlew clean check
    - stage: mutation
      script: ./gradlew clean pitest
